version: '3.7'

services:
  parkour-database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: light_parkour
      POSTGRES_DB: light_parkour
    volumes:
      - db_data:/var/lib/postgresql/data

  paper-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - parkour-database
    ports:
      - "25565:25565"

volumes:
  db_data: