version: '3.7'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: bart
      POSTGRES_DB: bart_db
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data

  paper-server:
    image: marctv/minecraft-papermc-server:1.18
    container_name: paper-server
    environment:
      MEMORYSIZE: 1G
    depends_on:
      - database
    ports:
      - "25565:25565"
    volumes:
      - type: volume
        source: shared-artifacts
        target: /data/plugins

volumes:
  db_data:
  shared-artifacts: